import 'package:flutter/material.dart';

const primaryColor = Color(0xFF205D67);
const secondaryColor = Color(0xFF639A67);
const textColor = Color(0xFFFFFFFF);

// mode de fonctionnement des actionners

const String DEFAUT = 'Défaut';
const String NORMAL = 'Normal';
const String ACTIVE = 'Activé';
const String DEACTIVE = 'Deactivé';

const String CaS04 = DEFAUT;
const String CaOH2 = ACTIVE;
const String AirBlower1 = DEFAUT;
const String AirBlower2 = DEFAUT;
const String LiftingPump = DEFAUT;
const String TransitionLiftPump = DEFAUT;
const String InOutFiltr = DEFAUT;
const String InOutLav = DEFAUT;
const String Rov = DEFAUT;
const String CleaningRov = DEFAUT;
const String HighPressurePump = DEFAUT;
const String PumpHclNaclo3 = DEFAUT;
const String RegulatingPump = DEFAUT;
const String DistribPump = DEFAUT;
const String BackwashingPump = DEFAUT;
const String AntisludgingPump = DEFAUT;

const String Capt1 = ACTIVE;
const String Capt2 = ACTIVE;
const String Pression1 = DEACTIVE;
const String Pression2 = DEACTIVE;
const String IndCarbone = DEACTIVE;
const String IndFeMn = ACTIVE;
const String Conduct1 = ACTIVE;
const String Conduct2 = DEACTIVE;
const String Conduct3 = ACTIVE;
const String Th = ACTIVE;
const String Ph = ACTIVE;
const String Low_Float1A = ACTIVE;
const String High_Float1A = DEACTIVE;
const String Low_Float2A = ACTIVE;
const String High_Float2A = ACTIVE;
const String Low_Float1_1 = ACTIVE;
const String Medium_Float1_1 = DEACTIVE;
const String High_Float1_1 = ACTIVE;
const String Low_Float1_2 = ACTIVE;
const String Medium_Float1_2 = ACTIVE;
const String High_Float1_2 = DEACTIVE;
const String Low_Float1 = DEACTIVE;
const String Medium_Float1 = DEACTIVE;
const String High_Float1 = ACTIVE;
const String Low_Float2 = ACTIVE;
const String Medium_Float2 = ACTIVE;
const String High_Float2 = ACTIVE;

const String Status_P1_CaS04 = DEACTIVE;
const String Status_P2_CaS04 = DEACTIVE;
const String Status_A_CaS04 = DEACTIVE;
const String Status_P1_CaOH2 = ACTIVE;
const String Status_P2_CaOH2 = ACTIVE;
const String Status_A_CaOH2 = ACTIVE;
const String Status_AirBlower1 = ACTIVE;
const String Status_AirBlower2 = DEACTIVE;
const String Status_LiftingPump1 = ACTIVE;
const String Status_LiftingPump2 = DEACTIVE;
const String Status_TransitionLiftPump1 = DEACTIVE;
const String Status_TransitionLiftPump2 = DEACTIVE;
const String Status_InFiltrV1 = ACTIVE;
const String Status_InFiltrV2 = ACTIVE;
const String Status_OutFiltrV1 = DEACTIVE;
const String Status_InLavV1 = ACTIVE;
const String Status_InLavV2 = ACTIVE;
const String Status_OutLavV1 = DEACTIVE;
const String Status_OutLavV2 = DEACTIVE;
const String Status_Rov = DEACTIVE;
const String Status_CleaningRov = DEACTIVE;
const String Status_HighPressurePump = ACTIVE;
const String Status_PumpHclNaclo3 = ACTIVE;
const String Status_RegulatingPump = DEACTIVE;
const String Status_DistribPump1 = DEACTIVE;
const String Status_DistribPump2 = ACTIVE;
const String Status_BackwashingPump = ACTIVE;
const String Status_AntisludgingPump = DEACTIVE;
